### ISSUE TITLE
BuildConfig报红

### ISSUE THREAD

**Issue by georgeJzzz** [HuRuWo/UniXposed#3]
![image](https://user-images.githubusercontent.com/42543889/216912360-fd83c8fe-622c-481c-a70d-20b7bf3ad8fb.png)

你好，BuildConfig报红怎么处理呢？  能否出个demo。 
还有怎么hook特定的方法，并通过sekiro的rpc通信呢？
感谢

**Comment by DarkLineX** [comment]
新版as中去除了BuildConfig，可以新增一个设置选项
```
buildFeatures{
        buildConfig = true
    }
```
